name: publish docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v27

      - name: install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          # Add bun to the PATH permanently for subsequent steps
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: run bun install
        run: |
          bun install --no-progress --frozen-lockfile

      - name: fetch current hash of node_modules
        run: |
          # Calculate the hash of node_modules after running bun install
          HASH=$(sha256sum ./node_modules/* | sha256sum | awk '{print $1}')
          echo "Calculated node_modules hash: $HASH"
          # Update the outputHash in flake.nix with the new hash
          sed -i "s|outputHash = .*|outputHash = \"sha256-$HASH\"|" flake.nix

      - name: build docker image
        run: nix build -L .#dockerImage

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish docker image
        run: |
          docker load < result
          docker tag lurker:latest ${{ secrets.DOCKER_USERNAME }}/lurker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lurker:latest
