name: publish docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v27

      - name: build docker image
        run: nix build -L .#dockerImage

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish docker image
        run: |
          docker load < result
          docker tag lurker:latest ${{ secrets.DOCKER_USERNAME }}/lurker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lurker:latest
